[package]
name = "krypto_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
num-rational = "0.4.1"
once_cell = "1.19.0"
thiserror = "1.0.57"
